services:
  web:
    build: ./web
    ports:
    - "4200:4200"

  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
    - "4500:8080"
    - "4501:8081"
